defpath("/Applications/Gama_1_7.app")
rootexperiment <- getmodelparameter("examples/sir.gaml","sir")
outputs <- getoutputnames(rootexperiment)
parameters <- getparameternames(rootexperiment)
experimentclone1 <- setparametervalue(rootexperiment,parameters[1],990)
experimentclone1 <- setparametervalue(experimentclone1,parameters[2],10)
experimentclone1 <- setparametervalue(experimentclone1,parameters[3],0)
experimentclone1 <- setparametervalue(experimentclone1,parameters[4],.3)
experimentclone1 <- setparametervalue(experimentclone1,parameters[5],.1)
experimentclone1 <- setoutputframerate(experimentclone1,"susceptibles",1)
experimentclone1 <- setfinalstep(experimentclone1,2000)
experimentclone2 <- setparametervalue(experimentclone1,parameters[1],995)
experimentclone2 <- setparametervalue(experimentclone2,parameters[2],5)
experimentplan <- addtoexperimentplan(experimentclone1)
experimentplan <- addtoexperimentplan(experimentplan,experimentclone2)
startexperimentplan(experimentplan,hpc=1)

