defpath("/Applications/Gama_1_7.app")
rootexperiment <- getmodelparameter("examples/sir.gaml","sir")
#rootexperiment <- getmodelparameter("sir.gaml","sir")
outputs <- getoutputnames(rootexperiment)
parameters <- getparameternames(rootexperiment)
experimentclone1 <- setparametervalue(rootexperiment,"S",990)
experimentclone1 <- setparametervalue(experimentclone1,"I",10)
experimentclone1 <- setparametervalue(experimentclone1,"R",0)
experimentclone1 <- setparametervalue(experimentclone1,"beta",.3)
experimentclone1 <- setparametervalue(experimentclone1,"gamma",.1)
experimentclone1 <- setoutputframerate(experimentclone1,"susceptibles",1)
experimentclone1 <- setfinalstep(experimentclone1,2000)
experimentclone2 <- setparametervalue(experimentclone1,"S",995)
experimentclone2 <- setparametervalue(experimentclone2,"I",5)
experimentplan <- addtoexperimentplan(experimentclone1)
experimentplan <- addtoexperimentplan(experimentplan,experimentclone2)
startexperimentplan(experimentplan,hpc=1)

