library(gamar)
defpath("/Applications/Gama.app")
file.copy(paste0(system.file("examples",package="gamar"),"/sir.gaml"),".",T)
experiment1 <- getmodelparameter("sir.gaml","sir")
getparameternames(experiment1)
getoutputnames(experiment1)
experiment1 <- setparametervalue(experiment1,"S0",990)
experiment1 <- setparametervalue(experiment1,"I0",10)
experiment1 <- setparametervalue(experiment1,"R0",0)
experiment1 <- setparametervalue(experiment1,"beta",.3)
experiment1 <- setparametervalue(experiment1,"gamma",.1)
experiment1 <- setoutputframerate(experiment1,"susceptibles",1)
experiment1 <- setfinalstep(experimentclone1,300)
experiment2 <- setparametervalue(experiment1,"S0",995)
experiment2 <- setparametervalue(experiment2,"I0",5)
experimentplan <- addtoexperimentplan(experiment1)
experimentplan <- addtoexperimentplan(experimentplan,experiment2)
names(experimentplan) <- paste0("experiment",1:2)
# running it manually:
outfiles <- startexperimentplan(experimentplan,hpc=2)
sim1 <- getoutputs(getoutputfile(outfiles[[1]]),"S")
with(sim1,plot(steps,output,type="l",lwd=2,col="blue",
               ylab="number of individuals"))
# alternatively, running it automatically:
output <- runexpplan(experimentplan,2)
with(output$experiment1,plot(step,I,type="l",lwd=2,col="red"))
