library(gamar)
defpath("/Applications/Gama.app")
file.copy(paste0(system.file("examples",package="gamar"),"/sir.gaml"),".")
experimentclone1 <- getmodelparameter("sir.gaml","sir")
getoutputnames(experimentclone1)
getparameternames(experimentclone1)
experimentclone1 <- setparametervalue(experimentclone1,"S0",990)
experimentclone1 <- setparametervalue(experimentclone1,"I0",10)
experimentclone1 <- setparametervalue(experimentclone1,"R0",0)
experimentclone1 <- setparametervalue(experimentclone1,"beta",.3)
experimentclone1 <- setparametervalue(experimentclone1,"gamma",.1)
experimentclone1 <- setoutputframerate(experimentclone1,"susceptibles",1)
experimentclone1 <- setfinalstep(experimentclone1,2000)
experimentclone2 <- setparametervalue(experimentclone1,"S0",995)
experimentclone2 <- setparametervalue(experimentclone2,"I0",5)
experimentplan <- addtoexperimentplan(experimentclone1)
experimentplan <- addtoexperimentplan(experimentplan,experimentclone2)
outfiles <- startexperimentplan(experimentplan,hpc=2)
# Extract the S values (corresponding to THE getoutputnames(experimentclone1) )
sim1 <- getoutputs(getoutputfile(outfiles[[1]]),getoutputnames(experimentclone1))
sim1[c(1:3,(nrow(sim1)-2):nrow(sim1)),]
with(sim1,plot(steps,output,type="l",lwd=2,col="blue",
               ylab="number of individuals"))
