library(gamar)
defpath("/Applications/Gama.app")
experiment1 <- getmodelparameter(
  paste0(system.file("examples",package="gamar"),"/sir.gaml"),"sir")
getparameternames(experiment1)
getoutputnames(experiment1)
experiment1 <- setparametervalue(experiment1,"S0",990)
experiment1 <- setparametervalue(experiment1,"I0",10)
experiment1 <- setparametervalue(experiment1,"R0",0)
experiment1 <- setparametervalue(experiment1,"beta",.3)
experiment1 <- setparametervalue(experiment1,"gamma",.1)
experiment1 <- setoutputframerate(experiment1,"susceptibles",1)
experiment1 <- setfinalstep(experiment1,300)
experiment2 <- setparametervalue(experiment1,"S0",995)
experiment2 <- setparametervalue(experiment2,"I0",5)
experimentplan <- addtoexperimentplan(experiment1)
experimentplan <- addtoexperimentplan(experimentplan,experiment2)
output <- runexpplan(experimentplan,2)
with(output[[1]],plot(step,I,type="l",lwd=2,col="red"))
